### ISSUE TITLE
When a topic is selected and dragged to the edge of the map window, the map should shift in that direction to create more open space.

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#196]
This would compliment issue #194 . It is also what I intuitive expect to happen.

**Comment by Connoropolous** [comment]
@Bortseb if you want to bounce ideas around about a technical approach to this, just ping me and we'll have a quick chat

**Comment by Bortseb** [comment]
Hey, so I played with coding this last night... I am able to detect when a  
topic is dragged to the edge...and then translate the canvas...But I need a  
good way of continuing the translate the canvas as they continue to hold  
the topic at the edge. (My basic code works only if they continue to move  
the mouse around near the edge)I was thinking that I could translate the  
canvas by an increment on a timer that is initiated when they first enter  
the region... which is turned off once they release the metacode or leave  
the edge region... Is there a preferred way to do this?... and also a way  
to store this &quot;translate canvas&quot; state that gets turned off as  
described above?...One other thing... based on how onDragMoveTopicHandler  
works... the user doesn&#39;t really have to drag a topic for it to fire...  
a simple click on a topic is enough... this means if a user even just  
clicks on a topic near enough to the edge, the canvas will translate...  
this isn&#39;t exactly ideal, but I don&#39;t know how to fix this besides  
making this handler more &quot;correct&quot; somehow.
On Sat, 1 Oct 2016 at 12:21 Connor Turland &lt;notifications@github.com&gt;  
wrote:@Bortseb if you want to bounce ideas around about a technical  
approach to this, just ping me and we&#39;ll have a quick chat

—You are receiving this because you were mentioned.Reply to this email  
directly, view it on GitHub, or mute the thread.

**Comment by devvmh** [comment]
I have a couple of ideas for that

You can use window.setInterval and window.clearTimeout to define a function that repeats periodically. You can call setInterval with the translate function, and store its return value in a variable on one of the many Metamaps objects. Then in the listener for mouseup or whatever when the topic stops being dragged, you can call clearTimeout to stop the canvas from moving any more.

That can make a nice minimum viable product for this issue for sure, but addressing the next issue is tricky too. The next PR/commit would have to figure out a way to check how far the topic has moved since the function was last called, and also check if it's still near the edge of the screen. It could use that logic to decide whether it should start/stop translating the canvas again

I think this is doable with that approach, but I can't vouch for it being the best solution!

https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setInterval

**Comment by Bortseb** [comment]
See PR #724 for progress

**Comment by Bortseb** [comment]
see #724 , this is now done
