### ISSUE TITLE
Set map thumbnail to show up for map URL's rich summaries on other sites

### ISSUE THREAD

**Issue by poietic** [metamaps/metamaps#395]
...like FB, twitter, even on Embed.ly. Currently it only shows the profile photo of the creator of the map...

**Comment by Connoropolous** [comment]
Also include all these properties within the head tag...

![screen shot 2015-02-19 at 10 17 41 pm](https://cloud.githubusercontent.com/assets/1409121/6280985/45654f46-b885-11e4-8676-9e561a936de0.png)

**Comment by Bortseb** [comment]
I think we should make the selection of the map's thumbnail more of an intentional action.. i.e. it gets its own bit of UX, instead of getting lumped in with the "take screenshot" button... Its not obvious that taking a screenshot will also determine the thumbnail...

Is the thumbnail used in our own explore maps intended to be the same as that used in rich snippets/summaries?

Thinking even more deeply about this, why must the thumbnail be a snapshot of the map? What if the user wanted to use another image, of their own choosing, to be the quick visual that gets associated with their map "at a glance".. This is sorta like its own "metacode" in a way... People will remember their favorite maps most easily by their thumbnails... I would hate for this type of deep association to get lost because someone just clicks on the "take screenshot" button one day...

and I know all of this design thinking likely doesn't belong here... this will have to get shared somewhere else too... But I'm having many related thoughts, so I'll just get them down here...

I know rich snippets typically pic up on the content within a page (i.e. the first or most prominent image)... so we might do something similar with topics that represent metamaps... i.e. images from within the markdown of their descriptions could be what we grab onto for default thumbnails.... I also think it would be neat if the description within a topic of type metamap were linked to the description in the map info box on that map... (i.e. whats the difference between a map info box, and the topic card of that map that is on another map?

Ok, took this way too far... but will repost it in the design channel on slack.

**Comment by devvmh** [comment]
I was thinking that now  that export works, maybe the take a screenshot
action could be moved into the export dialogue, and the set thimbnail
action coukd be noved into the map card

I think this makes a lot of sense
