### ISSUE TITLE
add a keyboard shortcut for 'new topic' and then use auto-layout for placement

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#413]
the auto layout functionality is already built, it places new topics in a spiral, when you pull them in through the search bar

**Comment by devvmh** [comment]
Ben suggested another idea: once you're ready to create a topic, hit some key to automatically create the topic and pop up the carousel again. This seems related

We thought of tab/shift-tab, but those are taken by carousel spinning

I suggested Shift-Enter or Ctrl-enter for Ben's suggestion. These would work for Connor's too

Maybe the most elegant solution is Enter Enter. If you hit Enter on the map, it'll open the carousel. Then if you hit Enter Enter with the carousel open and a title entered, it'll create the topic and open the carousel again.

Enter Enter would only work if it didn't interfere with autocomplete and was fairly quick to pop up the carousel again; otherwise we'd want a dedicated function for Ben's suggestion

@Bortseb thoughts?

**Comment by Connoropolous** [comment]
My latest PR, #643 kind of takes care of this for now. Open the carousel once, pin it open, and then get the auto-placement taking care of positioning. There could still be, in my PR, the addition of a keyboard shortcut to open it up and pin it perhaps, but I'm going to close this for now, once my PR goes in...
