### ISSUE TITLE
Ecosystem level interoperability platform functionality

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps#425]
https://github.com/metamaps/metamaps_gen002/issues/430 expand groups and people metadata
https://github.com/metamaps/metamaps_gen002/issues/38 let user claim person topic as them
https://github.com/metamaps/metamaps_gen002/issues/431 JSON-LD map output at API endpoint
https://github.com/metamaps/metamaps_gen002/issues/429 adopt any common UI/UX components
https://github.com/metamaps/metamaps_gen002/issues/428 enable metamaps as OAuth provider, enabling API calls and sign in with metamaps on other platforms  (DONE)
https://github.com/metamaps/metamaps_gen002/issues/432 enable linking of accounts with other collaborative platforms, making cross-platform data access and alter possible

**Comment by harlantwood** [comment]
This sounds awesome and excellent and exciting.  Any more on this?  Links to related issues / etc?

**Comment by devvmh** [comment]
Well, this is just the placeholder for the idea really. @Connoropolous I think will spearhead this idea. He's been hanging out with others with cool projects on the go recently, and people are excited about this as a concept. I believe Hylo and Loomio are projects were specific names I heard that we'll be aiming to interoperate well with.

@Connoropolous could fill you, and this issue's description, in much better! :D

**Comment by Connoropolous** [comment]
Okay @harlantwood @devvmh I added some issues :)

**Comment by harlantwood** [comment]
Thanks Connor!

Also seems related: https://github.com/valueflows/valueflows/issues/55

**Comment by harlantwood** [comment]
Super interested in #431 -- json LD interop seems like the very low hanging fruit to me, and much easier than the oauth cross platform accounts.  

We've been working since last we talked on [visualising IPFS data](https://github.com/ipfs/dataviz/issues/4).  The upcoming 0.4 release of IPFS will support linked data naitvely.  

Once you expose JSON-LD, we could archive it in IPFS, and visualize it from anywhere -- including client side visualizations running in IPFS itself.
