### ISSUE TITLE
radial view - create keyboard shortcut for centering a selected topic

### ISSUE THREAD

**Issue by poietic** [metamaps/metamaps#466]

**Comment by devvmh** [comment]
Here are the keyboard shortcuts according to https://docs.google.com/spreadsheets/d/1CPMH2h8BJYZLSDed1MpYJeHQ1fa_YI8cWkJ4v8iEnXg/edit#gid=1400801254

| Shortcut | Action |
| --- | --- |
| Ctrl+U | Center topic |
| Ctrl+Y | Reveal siblings |
| Ctrl+T | Center topic and reveal siblings |

Ben suggested in the doc to use Alt/Opt instead. 

I have two thoughts for making it more simple to remember. One is that in Word, etc, Ctrl+E is used to center *justify* text, so that's a potential one to use. The other is that if I imagine a motion to center on a topic, I imagine double clicking. That seems most natural for moving around a map. Heck, we could even use that on map and topic view.

There is a lot of possible dev work on that spreadsheet but for now I'll focus on centering with keyboard or mouse.

Another interesting question is raised in the spreadsheet about revealing siblings: what happens if you have multiple selected? Does it reveal all of the siblings? What about centering the map while you have multiple selected? 

Once I've taken a look at what's possible with JIT I'll post again with what I'll do/what I did.

**Comment by devvmh** [comment]
My current local branch is using the shortcuts in the table above. If there are no nodes selected or you're on Map view, there is no effect. If there are 1+ nodes selected, it uses the first element of the Metamaps.Selected.Topics array, whichever it is. 

1. Should I disable the functionality if there are multiple topics selected? it might be less confusing. Or maybe I should use the *last* element in the array (although I'm not sure if that's guaranteed to be the most recently selected one.
2. Do we want to change the shortcuts at all?
