### ISSUE TITLE
Allow JS to be written in / refactored to ES6 where desired

### ISSUE THREAD

**Issue by harlantwood** [metamaps/metamaps#508]
I personally like ES6 a lot and would like to make it part of our pipeline.  Interested to hear thoughts from the core team on this off course.

**To do this within the rails project**, the minimal way is: https://github.com/TannerRogalsky/sprockets-es6

But we might also consider jumping to the react/rails solutions, which seem to have a lot more momentum, and give us ES6 for free asking the way:
- https://github.com/reactjs/react-rails is the basic version
- https://github.com/shakacode/react_on_rails also gives us webpack, redux and more

**To do this in a separate front end repo**, there are many options.  I suggest starting here: https://github.com/dignifiedquire/dignified.js for an opinionated set of great defaults.

**Comment by devvmh** [comment]
Here are my thoughts about ES6:

1. I recently started using ES6/React at work, and I love it. I was confused by the syntax at first, but it is very Ruby-like and does a lot of great stuff. Once I got past the initial learning curve, it started being very enjoyable to program with ES6
2. I've been considering the pros/cons of adding a compile step to our Javascript (other than rails' assets:precompile). I worked on another rails app that had a compile step for React JSX components, and I found it wasn't well documented and it was hard to remember how to compile. It also wasn't immediately apparent to the beginning developer (me at the time) how to work with the src/ and dist/ directories. However, there are obvious benefits to using Babel
3. I also recently dove into the ES6/React/Redux rabbit hole, learning how to build a single page application with react-redux, backed by an api. I eventually got over the learning curve, but it was a pretty horrible experience for me as a developer. The rate of churn is so high. It may be currently settling down, but I don't think these technologies are mature enough yet for "non-elite" developers.
4. And another point that ties in: we do have a ([now stated!](https://github.com/metamaps/metamaps_gen002/pull/490/files)) goal to be a project that supports beginning developers starting out with web development, offering some mentorship in exchange for code contributions. I think it's important to keep our stack as easy-to-use as possible. The availability of consistent documentation on the internet is a big factor here. Rails really shines here. ES6 struggles here, not because it's not great, but because it's new and is still competing with ES3 and other syntax variants.
5) The move to ES6 would be a lot of work with minimal maintainability benefits.

So given these points together, I'm currently opposed to moving to ES6 for metamaps. I agree it would be great, but I don't think it's a priority like Rails 4 was.

-------

If someone were willing to do the work, it would definitely change the decision. But even then, adding the tooling steps does increase the barriers to entry for contributing to Metamaps. Ruby on Rails developers will be intimidated by ES6, but I don't think ES6 developers will be intimidated by Ruby or our current style of Javascript.

Additionally, @Connoropolous and I are both interested in incorporating React at some point. It's not an urgent thing, but we are enthusiastic about the idea of replacing existing components with React components. Once we do incorporate React, we will almost certainly need some polyfills and tooling. This will be another factor that makes a move to ES6 more attractive to me.

Slightly off topic: if you (or anyone else reading this issue) has any experience using Backbone and React, I've been seriously considering that as a path to take. It seems like it offers a lot more than Redux, but I'd love to hear about the downsides

**Comment by devvmh** [comment]
Those three libraries look awesome

**Comment by Connoropolous** [comment]
Great points Devin... For the time being, I am totally with you on all of
that

On Sunday, March 27, 2016, Devin Howard <notifications@github.com> wrote:

> Those three libraries look awesome
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps_gen002/issues/508#issuecomment-202042024>
>


-- 
Connor Turland
~to craft a sustainable and thriving culture within and without myself~
co-creator of Metamaps.cc

**Comment by harlantwood** [comment]
Thanks for your thoughtful response Devon.

I agree that we should wait until a React upgrade for the React toolchains.

I don't agree about the basic level though, which is:
https://github.com/TannerRogalsky/sprockets-es6

If it works well (I haven't tried it), it should integrate seamlessly into the asset pipeline (future versions of sprockets will do es6 out of the box).

As to beginning developers, I think we would be doing them a favor to expose them to es6, which is now last year's standard,  and is IMO very well documented, and is certainly an important skill for future development work.

Lots of other stuff I'm working on, so I'm probably not in danger of doing this too soon, but I do encourage this direction.

**Comment by devvmh** [comment]
Thats cool - if you can get es6 syntax with ni compile step, thatll be
awesome

I'll check out es6 sprockets during my refactoring project

**Comment by harlantwood** [comment]
Awesome!  :smile:

**Comment by devvmh** [comment]
All right, the feature/rails5-untested branch now has es6 code transpiling properly. I haven't tested it works, but it does transpile successfully.

I'm happy with moving this into the backlog now. However, when looking at sprockets-es6 it seemed smarter to just jump to sprockets 4. In order to make that work, I needed to bump a bunch of gems to beta/rc versions:

    gem 'rails', '~> 5.0.0.rc2'
    gem 'sass-rails', '~> 6.0.0.beta1'
    gem 'sprockets', '~> 4.0.0.beta2'

I'm guessing that rails 5 will be shipping in a month or two, and I'm hoping that sass and sprockets will both release their new versions later this year. Once these three gems are released as production-ready, we can use feature/rails5-untested as a starting point to upgrade to rails 5 (which will make @Connoropolous happy) and at the same time enable es6 transpilation (which will make @harlantwood and me happy).

One sidenote: sprockets 4 uses the babel-transpiler gem, which relies on the babel-source gem, which is still on version 5.8.35 (babel is currently working on 6.11). These gems don't seem particularly well maintained. I'm hoping that the rails core team will eventually address that, or remove the babel-transpiler dependency in favour of something better.

In the worst case though, we could start compiling our javascript ourselves, so when these three gems release we'll be set to start using es6.

@Connoropolous if you want to see es6 in action, here's the example code I was testing in Metamaps.Create.es6: https://github.com/metamaps/metamaps/compare/develop...feature/rails5-untested#diff-a9c3bd311eab80c9ebe6a69830f9ad02L49

**Comment by Connoropolous** [comment]
Right on @devvmh! that's some serious stuff. I still haven't gotten into Es6 so it feels a bit over my head, but I'm not worried about that. I am definitely interested in the simplicity of making realtime updating front-ends in rails 5, so this is sweeet!

**Comment by devvmh** [comment]
Yeah. The update to rails 5 is mostly smooth except for there's a breaking
change in ActiveModel::Serializer that means we can't use `embed :ids,
include: true`, so we can't merge this yet. Rails 5 is due in the fall, as
it turns out, so if you're interested take a closer look at this branch and
see if you can fix any problems.

ES6 is just a bonus that comes with the move to rails 5, really.

**Comment by harlantwood** [comment]
Great work : )

**Comment by devvmh** [comment]
Updates:

1. rails 5 update isn't going great because of changes to ActiveModel::Serializer
2. I'm leery of the sprockets-es6 approach because the babel-transpiler gem isn't well maintained
3. I just now discovered https://github.com/fnando/babel-schmooze-sprockets, which will be my next line of inquiry
4. In the meantime, we've added a frontend/ folder that is hooked into teh asset pipeline (but with a build step). If I could replace this with babel-schmooze-sprockets, I will be very happy.

**Comment by devvmh** [comment]
Update: babel-schmooze-sprockets seems nice but I don't see how it integrates with npm, which is what we'd need. Perhaps webpack-rails or browserify-rails would do the trick? For now our frontend folder is working fine though.

**Comment by devvmh** [comment]
ok at work i solved this problem by using browserify-rails. it's possible to set up a build that

1. allows npm imports/requires
2. allows es6 syntax in all files
3. also allows coffeescript if you swing that way (which we don't at metamaps)
4. doesn't require an extra build step

I'm thinking I'll try to get it merged at work and test it out to see if there are disadvantages. I'm finally starting to think about the size of our application.js, for instance

**Comment by devvmh** [comment]
now this is REALLY closed using https://github.com/metamaps/metamaps/pull/649
