### ISSUE TITLE
Fork map / save to new map is broken currently

### ISSUE THREAD

**Issue by G1TB3N** [metamaps/metamaps#540]
Tried this on two maps, via two different users, on two browsers, all getting the "working..." notification briefly but then no result. Connor noted a 'server error' mssg, and will check the log

**Comment by Connoropolous** [comment]
I just want to make a note to self, and to @devvmh on this one. 

I really like your implementation of 'MapExportService' Devin, and I think we should do the 'forking' of the map on the server side that same way, instead of passing data from the front end. it could even have its own URL/endpoint to perform that function, which we could call instead of 'create map' like we currently do. What do you think?

**Comment by Connoropolous** [comment]
@G1TB3N It's helpful if you assign a 'bug' label when you create something like this :) just a little tip

**Comment by devvmh** [comment]
@connor +1 for map_fork_service.rb with an api endpoint. Sounds glorious!

**Comment by Connoropolous** [comment]
Darn, the only complexity that i just remembered is that we send info from the front end because they may have moved things around on a public map, which wouldn't save, and then the fork would look like the non-adjusted map. 

I wanted the idea of 'save to new map' to be that it saves whatever you are currently seeing on your page as a new map, not an exact copy of the map as it exists in the DB.

**Comment by devvmh** [comment]
ok so

    POST /maps/:id/fork

with data like

    {
      mappings: [
        {
          mappable_type: "Topic",
          mappable_id: 4,
          x: 45,
          y: 46
        }
      ]
    }

What other keys would we need? We could treat this like a PATCH (or even make it a PATCH), and update the mappings. On a commons map, we wouldn't need to send any info. On a private map, same thing. On a public map, if they have edit permissions, we don't need to send anything. On a public map with no edit permissions, we include an array of mappings with new x/y values. Would we need other updates?

This is slightly worse than a frontend fork, because if we add new things that people can do we'll need to explicitly enable that in forking. Is that an acceptable tradeoff? Or is it better to keep the old behaviour?

Also, does forking currently create new topics or re-use the old topics?

**Comment by devvmh** [comment]
I'm going to try to make this work the old way for the v2.9 release, then we can open a new issue for the new way.

**Comment by Connoropolous** [comment]
Yes, agreed. Thanks Devin

On Tue, Apr 19, 2016 at 7:50 PM, Devin Howard <notifications@github.com>
wrote:

> I'm going to try to make this work the old way for the v2.9 release, then
> we can open a new issue for the new way.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps/issues/540#issuecomment-212175384>
>



-- 
Connor Turland
~to craft a sustainable and thriving culture within and without myself~
co-creator of Metamaps.cc
