### ISSUE TITLE
Split socket.io server into its own repo

### ISSUE THREAD

**Issue by harlantwood** [metamaps/metamaps#541]
This would make it possible to push to heroku, and shouldn't be much of a hardship when setting up on another server.

Interested to hear core dev thoughts pro or con.

**Comment by Connoropolous** [comment]
Yeah, it would be a good thing to happen probably. Give it some actual
love.

I have been dreaming of a larger overhaul of the websockets architecture
though, because now that data will also be created over the API some data
gets missed in the realtime streaming, as it just happens p2p between
people on the map.

I think we will always want the p2p for some things though, for
transmitting anything that's not being saved to the database.

We used to use Redis to create the bridge between Ruby and Node, but it
looks like in Rails 5 they have something called ActionCable which does
realtime streaming to the client out of the box.

So... I am a bit ambivalent about whether we move it to its own repo at the
moment :p
