### ISSUE TITLE
Bugs found while naming newly created map... and other comments

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#701]
When I create a new map, the map card pops up with a nice tooltip telling me to "Click here to name the map"

I have a bunch of comments about the changes that have happened here... and some bugs to point out too.

It surprised me that clicking the new map button now immediately creates the new map. I am a little worried that this might mean that new users never learn about our map permission types because of this, or never change the type from the current default "Public". (Or never add a description)

The bugs with how things work now are:
1. When I click the topic card to start entering my name, the tooltip doesn't disappear.
2. When I click to start entering my name, the previous text "Untitled Map" isn't automatically selected to be overwritten. (Or just deleted for me)

This isn't a bug but, it might also be nice to just put the cursor into the inbox for the user, so they can just start typing... even if the tooltip is kept to grab their attention.

**Comment by Connoropolous** [comment]
" I am a little worried that this might mean that new users never learn about our map permission types because of this, or never change the type from the current default "Public". (Or never add a description)" 
very valid concerns, I think you're totally right. this is an instance of development racing ahead of design. I'm not saying it's optimal, I'm saying it's something that's been happening because it feels better to have development happening regardless of whether design has been, so that things can keep moving forward. Once there is capacity within the network, or outside of it, to be thinking deeply about user experience and creating designs, then developers will be able to prioritize those UX and design changes. 

In the meantime, we are just barely holding on in terms of UX, around something like this new map create flow

**Comment by Connoropolous** [comment]
in the meantime, we could make some of the simple changes that you proposed, because it seems like they will benefit the user and cause no harm

**Comment by Connoropolous** [comment]
Also on this note... 
"It surprised me that clicking the new map button now immediately creates the new map. I am a little worried that this might mean that new users never learn about our map permission types because of this, or never change the type from the current default "Public". (Or never add a description)"

the reason I made this change is because I am less worried about those second step things not happening, than new users not even creating a map because they were inhibited by the initial popup

**Comment by Bortseb** [comment]
I'm not trying to be critical of anyone in any way... Just added this so
that its on our list somewhere...

I don't really know what you mean by "inhibited by the initial popup" ...
You mean people would hit that page and be more reluctant to start a map?

Will the tool tip stay up even if the user starts mapping instead of first
naming their map? (if not  we could wind up with a lot of untitled maps...
Maybe there is a better default namr? So then, even if the user doesn't
choose a name...  It is still given a unique name... )

**Comment by devvmh** [comment]
Yeah i think it wpuld be nice to call.new maps Map 999 or whatever

I think focusing the input and selecting the text with jquery on page load
is a good idea too

**Comment by devvmh** [comment]
FWIW, user experience-wise, I think creating the new map immediately is way better for the end user than a popup box. You shouldn't need to title something before creating it. 

Perhaps we could implement a few things to solve these problems:

1. After adding a title to a map (i.e. changing it from Untitled Map/Map 999), perhaps we could pop up a message asking them if they'd like to a) add their map to the global commons, b) leave the map as publicly viewable, or c) make it private to prevent others seeing it. I'd guess that generally when titling a map (whether before your first topic, or after your 100th synapse is created), you'll have a sense of what permissions it could have
2. Hide maps with "Untitled Map" from the global view by default
3. Create a user setting for default map permission.
4. Remove the ?new from the url after the map info box is closed for the first time, so that refreshing the page won't pop it up again.
5. When ?new is in the url, focus and select the text of Untitled Map after popping up the info box to make it easier to immediately add a title.

These are all moderately simple changes. If we did do all of these (either for a Halloween or New Years release), would that solve this issue, or would other potential problems still be outstanding?

**Comment by Connoropolous** [comment]
"I'm not trying to be critical of anyone in any way... Just added this so
that its on our list somewhere..."

I know Rob :) I just didn't have a lot of time so I was getting straight to the point of what was on my mind when I read it.

**Comment by Connoropolous** [comment]
put this into my backlog :)

**Comment by Bortseb** [comment]
I agree, that just starting a map without naming it first makes a lot more
sense... This is how google documents works too... you create something
new, and just immediately start typing. (Name it later)... This is along
the same lines of "just create a topic, don't worry about assigning a
metacode/type to it until later"...

I think what the default is, in both these cases, is important... I am fine
with "Untitled Map", because it is a bit more of a prompt to give it a
name... But maybe we can tack on a #_____ at the end? (This makes me
wonder... whats the equivalent of "Untitled Map" for the metacodes... I
realize that its the last metacode used... But this isn't the same as an
un-metacoded state...)

And thinking about it now, I think its safe to put the cursor/focus to the
map title input box... in case they do want to name it right away.... But
then, if they just start mapping, they are likely to be using just their
mouse on the canvas anyways ... so its not a big deal that the input box
has the focus until then... We might even just leave that tooltip up until
they do click on there to give it a name, or if they enter a name right
away... Its not really in the way of mapping if it stays there... and it
will remain as a prompt for later.

**Comment by Connoropolous** [comment]
:) the change to the map creation process was inspired by google docs

**Comment by Connoropolous** [comment]
@Bortseb with the changes that have been made, what would you like to do with this issue?

**Comment by Bortseb** [comment]
Not up to speed with exact changes... But if I check out deployed heroku I
will see?

**Comment by Connoropolous** [comment]
Yep!

**Comment by Connoropolous** [comment]
But also check out https://github.com/metamaps/metamaps/pull/710 for commentary

**Comment by Bortseb** [comment]
Ok, so this issue is pretty much resolved for me... Though, out of it has sprung this issues, #723 , about "where" new maps are created...

The only little unresolved bit in my mind is whether untitled maps should be given an incremental default name... and whether they should be shown in the global list...

I actually think they should be shown in the global list... to even-more promote seeing who else is mapping, and popping in to chat/map with them.... If I start a new map, and start mapping without naming first.... even if I am open to others joining in with me, and I wind up mapping for hours... nobody will see me around until I name the map.

**Comment by Bortseb** [comment]
The original issue has been resolved. I will add a new issue for the new concerns.
