### ISSUE TITLE
# of contributors dissappear on the map card when #topics/synapses are large

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#735]

**Comment by Bortseb** [comment]
![image](https://cloud.githubusercontent.com/assets/1617130/19162611/8cb62134-8bc6-11e6-91a8-1fcd7abc6d70.png)

**Comment by Connoropolous** [comment]
Actually this has to do with it being a 'commons' map, because in public and private maps that person dropdown tells you who has access, not who's contributed. Others don't like it, but I suggest we don't revert it back, but try and move forward with a more user friendly UI/UX. I will look for where previous convo abt this has gone on

**Comment by Connoropolous** [comment]
this issue isn't an issue, closing in favor of an ongoing design conversation about the map info box
