### ISSUE TITLE
Capture screenshot bug - "No file" failure

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#736]
I was wondering why we have a screenshot button. Because most times I just capture my own screenshots rather than use a built in function.

So I wanted to see if we added anything special to the screenshot, but I am unable to download any screenshots. The DL fails each time with this error: "No file"
https://support.google.com/chrome/answer/2898334?visit_id=1-636113737793569203-4246789472&hl=en&rd=2#nofile

Is this capture screenshot button still directly tied to the thumbnail preview that appears on the map cards in explore view?

If we are going to start automating these thumbnails, instead of requiring the user to click this button... then I don't really see a strong reason to keep this capture screenshot button around. I would personally never use it... but maybe I am missing the use-case for others.

**Comment by devvmh** [comment]
1. I just updated the screenshot code, so probably I broked it. I'll take a look
2. It is directly tied to the thumbnail. In my last test, the thumbnail did work
3. I believe our last plan was to automate screenshots, but still allow manual capturing because in typical usage (e.g. Ben's usage) automatic wouldn't do what he wanted, and manual was better
