### ISSUE TITLE
Default name for new maps, and do they appear in the global list?

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#797]
I no longer think that we should add an incremental number to the default "untitled map"... (i.e. just leave it as such)

I do however think that all maps, even currently untitled ones, should show up in the global list so that others can be aware of them right away... and potentially choose to join in on the mapping.

**Comment by devvmh** [comment]
I agree with the first paragraph, but disagree with the second. I think it's better to filter out "Untitled Map" maps. If we were on an instance with a small number of users, I can see the value in all live maps showing up for serendipity. But I think on metamaps.cc in particular, it doesn't make sense. 

I recall we talked about having the map card pop up each time the owner loaded a map that didn't have a title yet, to encourage titling it when ready. I support that idea.

**Comment by Connoropolous** [comment]
+1 to Devins suggestion. Rob, does that work/ make sense with you?

**Comment by Bortseb** [comment]
But I think we ARE on an instance  with a small  number of users and are trying  to promote serendipity.

**Comment by Connoropolous** [comment]
feels like this one would be better talked out in live convo :)

**Comment by Bortseb** [comment]
sure! This is such a minute thing too, to be discussing... I'm fine with it not showing up... I guess the other thing is that a percentage of untitled maps will just be trash... so we don't want that flooding the front page of explore... I'm fine with keeping it so that untitled maps don't show up... Except for maybe the user that created it? Have we accounted for that case?

**Comment by Connoropolous** [comment]
moving this to 'needs discussion' milestone

**Comment by devvmh** [comment]
I know we dont have many users, but there's no shared context between those
users.  Personally,  everyone i might video chat with on metamaps is on
slack. When i said small instance , i meant a community where everyone
mostly knows everyone else.

I think the analogy should be slack,  not chatroulette, you know?

Same goes for promoting serendipity; I'm just not convinced I'll have a
chat with someone i don't know on metamaps because i was intrigued by their
"untitled map". once map has a title,  I'm still not totally convinced,
 but it does seem a little more likely. in fact,  I'd even argue that
finding filtering by title makes me more likely to browse through global
maps (and potentially join someone's  map) because it wont be cluttered

I also think we have other great tools that are more effective to promote
serendipity.

PS i am articulating all this for the ffirs time so am very open to being
comvinced otherwise still. but as of right now I'm still not convinced
based on pros and cons
