### ISSUE TITLE
v3.0 firefox zoom bug

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#904]
"scroll zoom on any map in firefox creates stutter image trail"- BenB

I would try reverting these changes #738  , I noticed a similar bug while testing this code to get it to work... but I only tested on chrome.

**Comment by devvmh** [comment]
I tested the other day,  and it's #691

**Comment by Connoropolous** [comment]
so @Bortseb the breaking difference is that your code made use of `event.x` and `event.y` instead of `event.pageX` and `event.pageY` like found in the other functions that get called from mouse events. this is a browser difference between chrome and firefox, but pageX and pageY are used by both. I've made mistakes like this hundreds of times, it can be super tricky. let's watch out for ones like this in the future though! 
https://github.com/metamaps/metamaps/blob/develop/frontend/src/Metamaps/Realtime/index.js#L278

**Comment by Connoropolous** [comment]
for the record:

![surfin](https://cloud.githubusercontent.com/assets/1409121/19953854/f849a2c6-a12f-11e6-837a-f164fe2933e1.jpg)
![light speeeeeeeeddddd](https://cloud.githubusercontent.com/assets/1409121/19953855/fb6d9eb2-a12f-11e6-9916-c601b1be8f54.jpg)
![what we don t know we don t know](https://cloud.githubusercontent.com/assets/1409121/19953856/feb992e2-a12f-11e6-9125-4f66e18588c9.jpg)
![open source](https://cloud.githubusercontent.com/assets/1409121/19953859/015c3efa-a130-11e6-8875-b98373444a27.jpg)
![screen shot 2016-10-31 at 2 13 51 pm](https://cloud.githubusercontent.com/assets/1409121/19953863/04977e7c-a130-11e6-870b-e5f8b9d6a709.png)
